Nvt 396 exercicio1 backend
lilianns/exerciciosPHP pull request #2
Opened 2023-04-03 19:09 UTC by lilianns

2023-04-03 20:06 UTC, lilianns commented
Este PR depende da aprovação do #1

2023-04-22 13:16 UTC, edmargomes requested changes

2023-04-22 13:16 UTC, edmargomes commented on Exercicio1/index.php
> +    $resultado = $soma - 5;
- [ ] Inserir identação nas linhas 35 e 37 (+ 1 tab)
- [ ] Colocar o else na proxima linha
```
}
else {
    ....
}
```

2023-04-22 13:16 UTC, edmargomes commented on Exercicio1/index.php
> +}
Adicionar + tab para ficar alinhando com o if que foi aberto

2023-04-22 13:16 UTC, edmargomes commented on Exercicio1/index.php
> +    $resultado = $soma - 5;
Todo o codigo dentro do primeiro if precisar de ter mais um tab de identação.

2023-04-25 14:15 UTC, edmargomes approved these changes
Aprovado, mas faltaram pequenos pontos de identação, reforçamos no exercicio2

2023-04-25 14:15 UTC, merged